# 5. 오차역전파법
신경망이 가중치 매개변수에 대한 손실 함수의 기울기를 수치 미분을 사용해 구했다.   
하지만 수치 미분은 단순하지만 계산 시간이 오래 걸린다는 단점이 있다.   
가중치 매개변수의 기울기를 효율적으로 계산하는 오차역전파법을 배워보자.

# 5.1 계산 그래프
계산 과정을 그래프로 나타낸것을 __계산 그래프__라고 한다.   
그래프 자료구조는 여러 노드와 엣지로 표현된다.   
간단한 예시를 통해 차근차근 알아보자.

### 5.1.1 계산 그래프로 풀다
문제 1. 슈퍼에서 1개에 100원인 사과를 2개 샀습니다. 이때 지불 금액을 구하세요. 소비세 10%가 부과됩니다.   
![](https://blog.kakaocdn.net/dn/biHgge/btqIyea02FF/u5P7jDQgSCPa9D3RMPGnOK/img.png)

문제 2. 슈퍼에서 사과 2개, 귤 3개를 샀습니다. 사과는 1개에 100원, 귤을 1개에 150원 입니다. 소비세가 10%일 때 지불 금액을 구하세요.   
![](https://blog.kakaocdn.net/dn/bpjCkU/btqIwZkLAfb/iY8xeXo1deO4RqobY2QKKk/img.png)

위의 예제와 같이 계산 그래프를 이용한 문제는 다음 흐름으로 진행된다.   
1. 계산 그래프를 구성한다.
2. 그래프에서 계산을 왼쪽에서 오른쪽으로 진행한다.

여기서 2번에 해당되는 진행 단계를 순전파라고 한다.   
반대로 오른쪽에서 왼쪽으로 진행되는 것을 역전파라고 한다.

### 5.1.2 국소적 계산
계산 그래프는 국소적 계산을 전파함으로써 최종 결과를 얻는다.   
여기서 국소적이란 자신과 직접 관계된 작은 범위를 말한다.   
전체 계산이 아무리 복잡하더라도 각 단계에서 하는 일은 해당 노드의 국소적 계산이다.   
국소적인 계산은 단순하지만, 결과를 전달함으로써 결국 복잡한 계산을 해낼 수 있게된다.

### 5.1.3 왜 계산 그래프로 푸는가?
계산 그래프는 국소적 계산으로 전체가 아무리 복잡해도 각 노드에서 단순한 계산에 집중하여 문제를 단순화할 수 있다.   
그리고 중간 계산 결과를 모두 보관할 수 있다.   
가장 큰 이유는 __역전파를 통해 미분을 효율적으로 계산할 수 있다.__   

사과 가격이 오르면 최종 금액에 어떤 영향을 끼치는지 알고 싶을때 어떻게 해야할까?   
'사과 가격에 대한 지불 금액의 미분'을 구하는 문제에 해당된다.   
사과 값을 $x$, 지불 금액을 $L$이라 했을 때 ${{\alpha L} \over{\alpha x}}$를 구하는 것이다.   
이는 사과 값이 아주 조금 올랐을 때 지불 금액이 얼마나 증가하는지 표시한 것이다.   

![](https://mblogthumb-phinf.pstatic.net/MjAxODA2MjNfMTQw/MDAxNTI5NzM2NTEzMzcz.qZSa133HKdSkflstjt9bxI2znQvhRs1c20sxj0RdX7Qg.DI2D8zxzu3fJ5G5dZ_6YVjKn2OaExmjMAg5dQDKlJFsg.PNG.ssdyka/fig_5-5.png?type=w2)

역전파 과정을 통해 미분을 한다.   
중간까지 구한 결과를 공유할 수 있어서 다수의 미분을 효율적으로 계산할 수 있다.   

계산 그래프의 이점을 다시 한번 정리하자면 __순전파와 역전파를 활용해 각 변수의 미분을 효율적으로 구할 수 있다.__

# 5.2 연쇄법칙
역전파는 국소적인 미분을 오른쪽에서 왼쪽으로 전달한다.   
이를 전달하는 원리는 연쇄법칙에 따른 것이다.   
연쇄법칙과 이것이 계산 그래프상의 역전파와 같다는 사실을 알아보자.

### 5.2.1 계산 그래프의 역전파
$y=f(x)$ 수식의 역전파를 계산 그래프로 확인해보자.   
![](https://blog.kakaocdn.net/dn/FggJa/btqIqmVta4z/hDrKdVzzvHX7wAElrQ0Q4K/img.png)

신호 $E$의 노드에 국소적 미분 $({\alpha y \over{\alpha x}})$를 곱한 후 다음 노드로 전달하는 것이다.

이러한 방식이 연쇄법칙의 원리로 미분 값을 효율적으로 구할 수 있다는 것이 역전파의 핵심이다.   

### 5.2.2 연쇄법칙이란?
연쇄법칙을 알기 위해 합성 함수부터 알아야 한다.   
__합성 함수__는 여러 함수로 구성된 함수이다.   
예를 들어 $z = (x+y)^2$는 $z = t^2$와 $t = x+y$로 두 개의 식으로 구성된다.

연쇄법칙은 합성 함수의 미분에 대한 성질이고 다음과 같이 나타낼 수 있다.   
> 합성 함수의 미분은 합성 함수를 구성하는 각 함수의 미분의 곱으로 나타낼 수 있다.

위 식은 ${\alpha z \over {\alpha x}}$ (x에 대한 z의 미분)은 ${\alpha z \over {\alpha t}}$ (t에 대한 z의 미분)과 ${\alpha t \over {\alpha x}}$ (x에 대한 t의 미분)의 곱으로 나타낼 수 있다.   

${\alpha z \over {\alpha x}} = {\alpha z \over {\alpha t}}{\alpha t \over {\alpha x}}$   
여기서 $\alpha t$를 지울 수 있다.   
${\alpha z \over {\alpha x}} = {\alpha z \over {\alpha x}}$   

연쇄법칙을 써서 미분 ${\alpha z \over {\alpha x}}$를 구해보자. 먼저 국소적 미분(편미분)을 구한다.   
${\alpha z \over {\alpha t}} = 2t$   
${\alpha t \over {\alpha x}} = 1$   

미분 공식을 통해 해석적으로 구했는데, 최종적으로 구하고 싶은 ${\alpha z \over {\alpha x}}$는 위에서 구한 두 미분을 곱해서 계산하면 된다.   
${\alpha z \over {\alpha x}} = {\alpha z \over {\alpha t}} {\alpha t \over {\alpha x}} = 2t * 1 = 2(x+y)$

### 5.2.3 연쇄법칙과 계산 그래프
![](https://blog.kakaocdn.net/dn/9U9J5/btqIvDCbsVv/mS9ZrimZQoD2Ghzu85HIcK/img.png)

노드로 들어온 입력 신호에 그 노드의 국소적 미분을 곱한 후 다음 노드로 전달한다.

가장 왼쪽의 역전파를 보면 연쇄법칙이 성립되어 $x$에 대한 $z$의 미분이 된다.   

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FBLeIk%2FbtqInOkpSrO%2FZriGfBidyOqeudtrwgWwnk%2Fimg.png)   
계산 그래프의 역전파 결과에 따르면 ${\alpha z \over {\alpha x}}$는 $2(x+y)$임을 확인할 수 있다.

# 5.3 역전파
덧셈과 곱셈 노드에 따른 역전파를 알아보자.

### 5.3.1 덧셈 노드의 역전파
$z = x+y$라는 식을 대상으로 역전파를 살펴보자.   
위 식의 미분은 다음과 같이 해석적으로 계산할 수 있다.   
${\alpha z \over {\alpha x}} = 1$   
${\alpha z \over {\alpha y}} = 1$   

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FweVPG%2FbtqIwZebgfD%2FbM9nRxwgTxym9kabDhoMaK%2Fimg.png)   
역전파에서는 상류에서 전해진 미분에 1을 곱하여 하류로 흘린다.   
덧셈 노드의 역전파는 1을 곱하기만 하면 되므로 __입력된 값을 그대로 다음 노드로 보낸다.__   

미분 값으로 ${\alpha L \over {\alpha z}}$이 됐는데, 이는 최종적으로 $L$이라는 값을 출력하는 큰 계산 그래프를 가정하기 때문이다.   
$z=x+y$ 계산은 큰 계산 그래프의 중간 어딘가에 존재하고, 상류로부터 전해져온 값을 의미한다.

구체적인 예로 '10+5=15'라는 계산이 있고, 상류에서 1.3이라는 값이 흘러온다. 이는 다음과 같이 표현된다.   
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FwryMw%2FbtqIs83pNrO%2FbQDbak0dicJeaklazsMGgk%2Fimg.png)

### 5.3.2 곱셈 노드의 역전파
$z = xy$라는 식을 생각해보자. 이 식의 미분은 다음과 같다.   
${\alpha z \over {\alpha x}} = y$   
${\alpha z \over {\alpha y}} = x$   

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcWoZmR%2FbtqIvXU9pEN%2FIiCVTyc4TrfxSJ7pNgjrr0%2Fimg.png)

구체적인 예로 '10x5=50'이라는 계산을 역전파로 해보자.   
이때 상류에서 1.3 값이 흘러온다.   
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbhqAsb%2FbtqInOxU0Uh%2FtoTOhOl8x5IXIvMGfrSlkk%2Fimg.png)

덧셈의 역전파는 상류의 값을 그대로 흘려보내서 순방향 입력 신호의 값이 필요하지 않았지만, 곱셈의 역전파는 순방향 입력 신호의 값이 필요하다.   
그래서 곱셈 노드를 구현할 때는 순전파의 입력 신호를 변수에 저장한다.

### 5.3.3 사과 쇼핑의 예
![](https://mblogthumb-phinf.pstatic.net/MjAxODA5MDlfMjU0/MDAxNTM2NDY5MTYyNzM0.NYHbHx8H7fvCbcRFH3Hd7fkvqiJ6MnrRe8Q_cFoOD90g.Ds-9h4CYQDxU4Y80m1PQDktedGIh6_nq-gWN-uQiZEkg.PNG.ssdyka/fig_5-17.png?type=w2)

# 5.4 단순한 계층 구현하기
![](https://mblogthumb-phinf.pstatic.net/MjAxODA2MjNfMTQw/MDAxNTI5NzM2NTEzMzcz.qZSa133HKdSkflstjt9bxI2znQvhRs1c20sxj0RdX7Qg.DI2D8zxzu3fJ5G5dZ_6YVjKn2OaExmjMAg5dQDKlJFsg.PNG.ssdyka/fig_5-5.png?type=w2)   
사과 쇼핑의 예를 파이썬으로 구현해보자.   
계산 그래프의 곱셈 노드를 MulLayer, 덧셈 노드를 AddLayer라는 이름으로 구현해보자.

### 5.4.1 곱셈 계층
곱셈 계층을 구현해보자.

In [1]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    
    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y
        return out
    
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x
        return dx, dy

In [2]:
apple = 100
apple_num = 2
tax = 1.1

# layer
mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

# 순전파
apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price) # 220

220.00000000000003


In [3]:
# 역전파
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


backward()가 받는 인수는 순전파의 출력에 대한 미분임을 주의하자.

### 5.4.2 덧셈 계층
덧셈 계층을 구현해보자.

In [4]:
class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, y):
        out = x + y
        return out
    
    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1
        return dx, dy

![](https://mblogthumb-phinf.pstatic.net/MjAxODA5MDlfMjU0/MDAxNTM2NDY5MTYyNzM0.NYHbHx8H7fvCbcRFH3Hd7fkvqiJ6MnrRe8Q_cFoOD90g.Ds-9h4CYQDxU4Y80m1PQDktedGIh6_nq-gWN-uQiZEkg.PNG.ssdyka/fig_5-17.png?type=w2)

위 이미지 상황을 구현해보자.

In [5]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

# layer
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

# forward
apple_price = mul_apple_layer.forward(apple, apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(all_price, tax)

# backward
dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)
dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(price)
print(dapple_num, dapple, dorange, dorange_num, dtax)

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


# 5.5 활성화 함수 계층 구현하기
계산 그래프를 신경망에 적용해보자.   
신경망을 구성하는 layer 각각을 클래스 하나로 구현하자.   
먼저 활성화 함수인 ReLU와 Sigmoid를 구현해보자.

### 5.5.1 ReLU 계층
![](https://blog.kakaocdn.net/dn/vgJna/btqQzRGmwcO/TK3KTMlz4CYag8rBTKfYkK/img.png)

순전파에서 $x$가 0보다 크면 역전파는 상류의 값을 그대로 하류로 흘린다.   
$x$가 0보다 작으면 하류로 0을 보낸다.

In [6]:
class ReLU:
    def __init__(self):
        self.mask = None
    
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        return dx

mask라는 인스턴스 변수를 가진다.   
이는 True, False로 구성된 넘파이 배열로 순전파 입력인 x의 원소 값이 0 이하인 인덱스는 True, 그외는 False로 유지한다.

역전파는 순전판때 만들어둔 mask를 써서, mask의 원소가 True일 경우에 상류에서 전파된 dout을 0으로 설정한다.

In [7]:
import numpy as np
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
print(x)
mask = (x <= 0)
print(mask)

[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]


### 5.5.2 Sigmoid 계층
![](https://t1.daumcdn.net/cfile/tistory/275BAD4F577B669920)



시그모이드 함수는 다음 식을 의미한다.   
$y = {1\over{1+exp(-x)}}$

시그모이드 계층의 계산 그래프는 '*', '+', 'exp', '/' 노드가 등장한다.   
'exp' 노드는 $y = exp(x)$ 계산을 수행하고 '/' 노드는 $y = {1\over{x}}$ 계산을 수행한다.

![](https://velog.velcdn.com/images%2Flilpark%2Fpost%2Fe4fc1d53-2443-477e-a9b0-3e5a9fae8eb3%2Fimage.png)

이를 계산 그래프에서 간소화하면 다음과 같이 나온다.   
![](https://velog.velcdn.com/images%2Flilpark%2Fpost%2F2b877b61-b267-4852-9022-a9da55c1db00%2Fimage.png)

${\alpha L \over {\alpha y}}y^2 exp(-x)$   
$= {\alpha L \over {\alpha y}}{1 \over {(1+exp(-x))^2}}exp(-x)$   
$= {\alpha L \over {\alpha y}}{1 \over {1 + exp(-x)}} {exp(-x) \over 1+exp(-x)}$   
$= {\alpha L \over {\alpha y}}y(1-y)$

위 계산식을 보면 sigmoid 계층의 역전파는 순전파의 출력 $y$의 값만으로 계산을 진행할 수 있게 된다. 그래서 다음과 같이 표현할 수 있게 된다.   

![](https://blog.kakaocdn.net/dn/bR5ka7/btrbN5cJFxP/u0hZweWlmhIHq6oGovvK51/img.png)

In [8]:
class Sigmoid:
    def __init__(self):
        self.out = None
    
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out

        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out

        return dx

위 구현에서는 순전파의 출력을 out 변수에 보관했다가, 역전파 계산할 때 그 값을 사용한다.

# 5.6 Affine/Softmax 계층 구현하기

### 5.6.1 Affine 계층
신경망의 순전파에서 가중치 신호의 총합을 계산하기 위해 행렬의 곱(np.dot())을 사용했다.   
예시를 확인해보자.

In [9]:
X = np.random.rand(2) # 입력
W = np.random.rand(2,3) # weight
B = np.random.rand(3) # bias

print(X.shape)
print(W.shape)
print(B.shape)

Y = np.dot(X, W) + B
print(Y.shape)

(2,)
(2, 3)
(3,)
(3,)


행렬곱의 핵심은 대응하는 차원의 원소 수를 일치시키는 게 핵심이다.   

> 신경망의 순전파 때 수행하는 행렬의 곱을 기하학에서 __어파인 변환(affine transformation)__ 이라고 한다.   
그리고 이것을 Affine 계층이라는 이름으로 구현해보자.

지금까지 계산 그래프의 노드에 스칼라값이 있었는데 이번엔 행렬이 흐르고 있다.   
여기에 역전파에 대해 생각해보자.   
행렬을 사용한 역전파도 행렬의 원소마다 전개해보면 스칼라값을 사용한 지금까지의 계산 그래프와 같은 순서로 생각할 수 있다.   

${\alpha L \over {\alpha X}} = {\alpha L \over {\alpha Y}} W^T$   
${\alpha L \over {\alpha L}} = X^t {\alpha L \over {\alpha Y}}$   

여기서 $T$는 전치행렬을 뜻한다.   
이는 $W$의 $(i, j)$ 위치의 원소를 $(j, i)$ 위치로 바꾼 것을 말한다.   

![](https://blog.kakaocdn.net/dn/bKEIN4/btqIs83DdjS/XITy2ucBrqdnn8prfmiNZK/img.png)   

스칼라값이 아닌 행렬 곱을 진행하기 위해 행렬의 형상에 주의해야한다.   

### 5.6.2 배치용 Affine 계층
데이터 N개를 묶어서 순전파하는 경우인 배치용 Affine 계층을 생각해보자.   

![](https://blog.kakaocdn.net/dn/cTcDvH/btqIxY66Rej/LGESmiYoG0tY32Ls2KyNvK/img.png)

입력인 $X$의 형상이 (N,2)가 됐다.   

편향을 더할 때 주의해야한다.   
순전파의 편향 덧셈은 $XW$에 대한 평향이 각 데이터에 더해진다.

In [10]:
X_dot_W = np.array([[0,0,0], [10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)

print(X_dot_W + B)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]


순전파에서 편향 덧셈은 각각의 데이터에 더해진다.   
그래서 역전파 때는 각 데이터의 역전파 값이 편향의 원소에 모여야 한다.

In [11]:
dY = np.array([[1,2,3], [4,5,6]])
print(dY)

dB = np.sum(dY, axis=0)
print(dB)

[[1 2 3]
 [4 5 6]]
[5 7 9]


이 예에서 데이터가 2개라고 가정했다.   
편향의 역전파는 두 데이터에 대한 미분을 데이터마다 더해서 구한다.   
그래서 np.sum()에서 0번째축에 대해 총합을 구하는 것이다.   

Affine 구현을 확인해보자.

In [12]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None

    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b

        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)

        return dx

### 5.6.3 Softmax-with-Loss 계층
출력층에서 사용하는 소프트맥스 함수에 대해 알아보자.   
소프트맥스 함수는 입력 값을 정규화하여 출력한다.   

손글씨 숫자 인식에서 다음과 같은 순서로 진행한다.   
> 입력 이미지가 Affine 계층과 ReLU 계층을 통과하며 변환하고, 마지막 Softmax 계층에서 10개(숫자 0~9)의 입력이 정규화된다.   
최종적으로 Softmax 결과의 값이 확률이 된다.

> 신경망은 학습과 추론 작업으로 나뉜다.   
추론은 일반적으로 Softmax를 사용하지 않는다.   
추론할 때는 마지막 Affine 계층의 출력을 인식 결과로 이용한다.   
신경망에서 정규화하지 않는 출력 결과를 __점수(score)__라고 한다.   
신경망 추론에서 답을 하나만 내는 경우에는 가장 높은 저무만 알면 되니 Softmax는 필요 없어진다.

소프트맥스 레이어를 구현하기 위해 손실 함수의 교차 엔트로피 오차도 포함하여 구현해보자.   
먼저 softmax-with-loss 계층의 계산 그래프를 살펴보자.   
![](https://i.imgur.com/UPTYfXt.png)

그리고 아래와 같이 간소화 할 수 있다.   
![](https://velog.velcdn.com/images/bbirong/post/018ee92a-af64-4239-b277-7ddf3add9e16/image.png)

3개의 클래스 분류를 가정하고 이전 계층에서 3개의 입력(점수)를 받는다.   
Softmax 계층은 입력 $(a_1, a_2, a_3)$을 정규화하여 $(y_1, y_2, y_3)$을 출력한다.   
Cross Entropy Error 계층은 Softmax의 출력과 정답 테이블 $(t_1, t_2, t_3)$을 받고, 이 데이터들로부터 손실 $L$을 출력한다.   

역전파의 결과를 보면 Softmax 계층은 $(y_1-t_1, y_2-t_2, y_3-t_3)$이라는 말끔한 결과를 얻는다.   
이는 Softmax 계층의 출력과 정답 레이블의 차분이다.   
신경망의 역전파에선 오차가 앞 계층에 전해진다.   
__이는 신경망 학습의 중요한 성질이다.__

신경망 학습의 목적은 신경망의 출력이 정답 레이블과 가까워지도록 가중치 매개변수의 값을 조정하는 것이다.   
그래서 신경망의 출력과 정답 레이블의 오차를 효율적으로 앞 계층에 전달해야한다.   
그래서 역전파를 통해 얻는 결과는 Softmax 계층의 출력과 정답 레이블의 차이로, 신경망의 현재 출력과 정답 레이블의 오차를 있는 그대로 드러내는 것이다.   

> Softmax 함수의 손실 함수로 Cross Entropy Error를 사용하니 역전파가 말끔히 떨어진다.   
이는 우연이 아닌 그렇게 설계되었기 때문이다.   
회귀의 출력층에서 사용하는 항등 함수의 손실 함수로 오차제곱합을 이용하는 이유도 이와 동일하다.

구체적인 예를 들어보자.   
정답 레이블이 (0, 1, 0)이고 Softmax가 (0.3, 0.2, 0.5)를 출력했다.   
정답 인덱스에 맞는 확률이 20%로 나와 신경망은 제대로 인식하지 못함을 말한다.   
이 경우 Softmax의 역전파는 (0.3, -0.8, 0.5)라는 커다란 오차를 전파한다.   
그래서 Softmax의 앞 계층들은 큰 오차로부터 큰 깨달음을 얻게 된다.   

정답 레이블이 (0, 1, 0), Softmax가 (0.01, 0.99, 0)일 때를 가정해보자.   
이 경우 Softmax 계층의 역전파가 보내는 오차는 비교적 작은 (0.01, -0.01, 0)이 된다.   
앞 계층으로 전달된 오차가 작으므로 학습하는 정도도 작아진다.

Softmax-with_Loss 계층을 구현한 코드를 확인해보자.

In [ ]:
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [13]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None # 손실
        self.y = None # Softmax 출력
        self.t = None # 정답 레이블

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size
        return dx

역전파 때는 전파하는 값을 배치의 수로 나눠서 데이터 1개당 오차를 앞 계층으로 전파하는 점을 주의하자.

# 5.7 오차역전파법 구현하기

### 5.7.1 신경망 학습의 전체 그림

### 5.7.2 오차역전파법을 적용한 신경망 구현하기

### 5.7.3 오차역전파법으로 구한 기울기 검증하기

### 5.7.4 오차역전바법을 사용한 학습 구현하기

# 5.8 정리